using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.ShipyardService;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Forge.ShipyardService.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardServiceGridWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private ShipyardServiceBoundUserInterfaceState _state = new();

    public event Action<List<ShipyardServiceMarkerKey>>? ApplyMarked;

    public ShipyardServiceGridWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RepairCheck.OnToggled += _ =>
        {
            GridMap.ShowRepair = RepairCheck.Pressed;
            RefreshSelection();
        };
        ReinforceCheck.OnToggled += _ =>
        {
            GridMap.ShowReinforce = ReinforceCheck.Pressed;
            RefreshSelection();
        };
        PlastitaniumCheck.OnToggled += _ =>
        {
            GridMap.ShowPlastitanium = PlastitaniumCheck.Pressed;
            RefreshSelection();
        };
        PartsCheck.OnToggled += _ =>
        {
            GridMap.ShowParts = PartsCheck.Pressed;
            RefreshSelection();
        };

        SelectAllButton.OnPressed += _ =>
        {
            GridMap.Selected.Clear();
            foreach (var marker in GridMap.Markers)
            {
                if (GridMap.IsVisible(marker.Action))
                    GridMap.Selected.Add(marker.Id);
            }

            RefreshSelection();
        };

        ClearButton.OnPressed += _ =>
        {
            GridMap.Selected.Clear();
            RefreshSelection();
        };

        ApplyButton.OnPressed += _ =>
        {
            var targets = new List<ShipyardServiceMarkerKey>();
            foreach (var marker in GridMap.Markers)
            {
                if (!GridMap.Selected.Contains(marker.Id) || !GridMap.IsVisible(marker.Action))
                    continue;

                targets.Add(new ShipyardServiceMarkerKey
                {
                    Entity = marker.Entity,
                    Tile = marker.Tile,
                    Action = marker.Action,
                    IsTile = marker.IsTile
                });
            }

            if (targets.Count == 0)
                return;

            ApplyMarked?.Invoke(targets);
        };

        GridMap.SelectionChanged += RefreshSelection;
        HintLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-grid-hint")));
        RefreshSelection();
    }

    public void UpdateState(ShipyardServiceBoundUserInterfaceState state)
    {
        _state = state;
        var shuttle = state.SelectedShuttle is { } net && _entMan.TryGetEntity(net, out var uid)
            ? uid
            : (EntityUid?) null;

        if (shuttle != GridMap.Shuttle)
            GridMap.SetShuttle(shuttle);

        var selectedKeys = new HashSet<(NetEntity Entity, Vector2i Tile, ShipyardServiceAction Action, bool IsTile)>();
        foreach (var marker in GridMap.Markers)
        {
            if (!GridMap.Selected.Contains(marker.Id))
                continue;

            selectedKeys.Add((marker.Entity, marker.Tile, marker.Action, marker.IsTile));
        }

        GridMap.Markers = new List<ShipyardServiceUpgradeMarker>(state.Markers);
        Title = state.Quote.HasShuttle
            ? Loc.GetString("shipyard-service-grid-window-title-named", ("name", state.Quote.ShuttleName))
            : Loc.GetString("shipyard-service-grid-window-title");

        GridMap.Selected.Clear();
        foreach (var marker in GridMap.Markers)
        {
            if (selectedKeys.Contains((marker.Entity, marker.Tile, marker.Action, marker.IsTile)))
                GridMap.Selected.Add(marker.Id);
        }

        RefreshSelection();
    }

    private void RefreshSelection()
    {
        var count = 0;
        var repairCost = 0;
        var upgradeCost = 0;
        var hasRepair = false;
        foreach (var marker in GridMap.Markers)
        {
            if (!GridMap.Selected.Contains(marker.Id) || !GridMap.IsVisible(marker.Action))
                continue;

            count += marker.Count;
            if (marker.Action == ShipyardServiceAction.Repair)
            {
                hasRepair = true;
                repairCost += marker.Cost;
            }
            else
            {
                upgradeCost += marker.Cost;
            }
        }

        var occupancy = hasRepair && _state.Quote.OccupancyDue ? _state.Quote.OccupancyFee : 0;
        var cost = ShipyardServicePricing.CapRepairTotal(repairCost, occupancy, _state.Quote.VesselPrice) + upgradeCost;

        SelectionLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("shipyard-service-grid-selection",
            ("count", count),
            ("amount", BankSystemExtensions.ToSpesoString(cost)))));
        ApplyButton.Disabled = count <= 0 ||
                               _state.Balance < cost ||
                               hasRepair && _state.Quote.RepairOnCooldown;
    }
}
